export { default as CartSvg } from "./cart.svg";
export { default as SearchSvg } from "./search.svg";
export { default as CloseSvg } from "./close.svg";
export { default as ArrowLeftSvg } from "./arrow-left.svg";
export { default as PlusSvg } from "./plus.svg";
export { default as GlobeSvg } from "./globe.svg";
export { default as DotVerticalFilledSvg } from "./dot-vertical-filled.svg";
export { default as ClockSvg } from "./clock.svg";
export { default as HouseSvg } from "./house.svg";